### ISSUE TITLE
Ability to use GITHUB_RUN_NUMBER env variable

### ISSUE THREAD

**Issue by derrickshowers** [yanamura/ios-bump-version#1]
Github provides [environment variables](https://docs.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables) that would be awesome to tie into this action. For instance, using `GITHUB_RUN_NUMBER` would in theory allow for bumping the build number (based on this value) and not having to commit back to master. Any idea how this can be added or supported with this action? I tried passing in to the `build-number` but doesn't seem to work (tried `$GITHUB_RUN_NUMBER`, `${GITHUB_RUN_NUMBER}`, ${{ env.GITHUB_RUN_NUMBER }}`). Any ideas? Thoughts?

**Comment by derrickshowers** [comment]
Actually I found the issue... submitted a PR if you're interested in bring in the changes. If not, I can just work off the forked version. Thanks!

**Comment by yanamura** [comment]
@derrickshowers Thank you for your Pull Request and Question!

Please try this.
```
build-number: ${{github.run_number}}
```
