### ISSUE TITLE
Can the action set the version from a outside file

### ISSUE THREAD

**Issue by yingtao-butterflymx** [yanamura/ios-bump-version#14]
Say I have a version.txt with a 2.0.0 inside, can the action support setting version from that file? 
Thank you!

**Comment by yanamura** [comment]
@yingtao-butterflymx Thank you, I added new feature, please try this!
https://github.com/yanamura/ios-bump-version/releases/tag/v1.3.0

**Comment by yingtao-butterflymx** [comment]
@yanamura Thank you very much!

**Comment by yingtao-butterflymx** [comment]
@yanamura Is it possible to skip bumping the version if the version in version.txt is the same as the project version?
