### ISSUE TITLE
Unable to resolve action `yanambra/ios-bump-version@v1`, repository not found

### ISSUE THREAD

**Issue by huangboju** [yanamura/ios-bump-version#18]
![image](https://user-images.githubusercontent.com/14818224/129428972-c4010994-800b-4651-b495-904dbf5decb0.png)

**Comment by yanamura** [comment]
@huangboju It seems typo.
please change `yanambra` to  `yanamura`

**Comment by yanamura** [comment]
v1 tag exists here
https://github.com/yanamura/ios-bump-version/releases/tag/v1
